packages:
  - .

# Build controls used by our tooling and CI docs
onlyBuiltDependencies:
  - "sharp"
  - "esbuild"
  - "@swc/core"
  - "protobufjs"
  - "@sentry/cli"
  - "unrs-resolver"

ignoredBuiltDependencies:
  - "@firebase/util"

strictDepBuilds: false